version: '3.8'

services:
  fastapi-app:
    container_name: fastapi-app
    build: .
    image: fast_api_base

    ports:
      - "4000:80"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    command: /bin/bash -c "/app/pre-start.sh && uvicorn app.main:app --host 0.0.0.0 --port 80 --reload"

  db:
    container_name: postgresql_db
    image: postgres:16

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 5050:80

  flower:
    image: mher/flower
    depends_on:
      - redis
      - celeryworker
    env_file:
      - .env
    environment:
       - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD?Variable not set}@redis:6379/0
    ports:
      - "5555:5555"

  celeryworker:
    image: '${DOCKER_IMAGE_CELERYWORKER?Variable not set}:${TAG-latest}'
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=${SERVER_HOST}
    build:
      context: .
      dockerfile: celery-worker.dockerfile

  celery-beat:
    build: .
    command: celery -A app.celery.worker beat -l info --uid=nobody --gid=nogroup -s /tmp/celerybeat-schedule
    volumes:
      - /tmp:/tmp
    depends_on:
      - celeryworker

  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD?Variable not set}
    ports:
      - "6379:6379"

volumes:
  postgres_data:
