version: '3.8'

services:
  fastapi-app:
    container_name: fastapi-app
    build: .
    image: fast_api_base

    ports:
      - "4000:80"
    volumes:
      - .:/app
    depends_on:
      - db
    command: /bin/bash -c "/app/pre-start.sh && uvicorn app.main:app --host 0.0.0.0 --port 80 --reload"

  db:
    container_name: postgresql_db
    image: postgres:16

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 5050:80

  queue:
    #image: rabbitmq:3
    # Using the below image instead is required to enable the "Broker" tab in the flower UI:
    image: rabbitmq:3-management
    #
    # You also have to change the flower command
    ports:
      - "5672:5672"
  
  flower:
    image: mher/flower
    depends_on:
      - queue
      - celeryworker
    env_file:
      - .env
    environment:
       - CELERY_BROKER_URL=amqp://guest@queue:5672//
    ports:
      - "5555:5555"

  celeryworker:
    image: '${DOCKER_IMAGE_CELERYWORKER?Variable not set}:${TAG-latest}'
    depends_on:
      - db
      - queue
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=${SERVER_HOST}
    build:
      context: .
      dockerfile: celery-worker.dockerfile

  celery-beat:
    build: .
    command: celery -A app.worker beat -l info --uid=nobody --gid=nogroup -s /tmp/celerybeat-schedule
    volumes:
      - /tmp:/tmp
    depends_on:
      - celeryworker

volumes:
  postgres_data:
